version: "3.0"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - compose-networks
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  compose-networks:
